apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-vote-back2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azure-vote-back2
    spec:
      containers:
      - name: azure-vote-back2
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back2
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote-back2
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-vote-front2
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: azure-vote-front2
    spec:
      schedulerName: test-scheduler
      containers:
      - name: azure-vote-front2
        image: microsoft/azure-vote-front:redis-v1
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote-back2"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front2
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-vote-front2